.github/workflows/audit.yml

Use built-in Github token to increase rate limit

T-680640: Use built-in Github token to increase rate limit

---

examples/connector/golang/golang_connector/main.go

fix(partner-sdk): updated the go example with the new proto changes

---

common.proto
connector_sdk.proto
destination_sdk.proto
examples/connector/java/build.gradle
examples/connector/java/src/main/java/connector/ConnectorServiceImpl.java
examples/destination/java/build.gradle
examples/destination/java/src/main/java/destination/DestinationServiceImpl.java

PR for changes in engineering tools (contains testing details also): https://github.com/fivetran/engineering/pull/178219

fix(partner_sdk): change proto version to v2

---

destination_sdk.proto
examples/destination/java/src/main/java/destination/DestinationServiceImpl.java

Closes: https://fivetran.height.app/T-699973

feature(partner_sdk): add example for max value in destination capabilities

---

examples/connector/golang/golang_connector/main.go
examples/connector/java/src/main/java/connector/ConnectorServiceImpl.java
examples/connector/python/main.py

Closes https://fivetran.height.app/T-718405
- Added a field missing in VisibilityCondition
- Added example usage of FieldSet
- Java connector -> Successful
- Python connector -> Successful

refactor(Partner_sdk): Improvement in examples

---

README.md
common.proto
common_v2.proto
connector_sdk_v2.proto
destination_sdk.proto
destination_sdk_v2.proto
examples/connector/golang/golang_connector/main.go
examples/connector/golang/scripts/compile_protos.sh
examples/connector/golang/scripts/copy_protos.sh
examples/connector/java/build.gradle
examples/connector/java/src/main/java/connector/ConnectorServiceImpl.java
examples/connector/python/build.sh
examples/connector/python/main.py
examples/destination/java/build.gradle
examples/destination/python/build.sh
examples/destination/python/main.py

- Moved new proto changes into separate file suffixed `_v2`
- Updated the example build file to consider the `_v2` files.

Separated proto updates files into v2 files

---

examples/destination/java/src/main/java/destination/DestinationServiceImpl.java
examples/destination/python/main.py

Links: https://fivetran.height.app/T-718406
**Description of change**
* Added a missing field `VisibilityCondition`
* Added example usage of `FieldSet`
**Testing done:**
* Python and Java examples are successful:

Refactor(fivetran_sdk): Improvement destination examples

---

destination_sdk_v2.proto
examples/destination/java/src/main/java/destination/DestinationServiceImpl.java
examples/destination/python/main.py

Links https://fivetran.height.app/T-725623

fix(Destination): Merge file params into one

---

development-guide.md

Closes https://fivetran.height.app/T-734564
Update Dev guide with user tasks description

doc(partner_sdk): Update Dev guide with user tasks description

---

tools/destination-tester/README.md

Links: https://fivetran.height.app/T-738840
Add CLI args detail in README

Update destination tester README

---

tools/connector-tester/README.md
tools/destination-tester/README.md

Links: T-749376
Updated tester document with single tester details.
Below CLI args are necessary to run the tester
* --port 
* --tester-type

feature(ft-sdk): document change for single tester

---

.github/workflows/audit.yml

Closes https://fivetran.height.app/T-705344

fix(workflow): fix python build

---

tools/connector-tester/README.md
tools/destination-tester/README.md

Fix the link to docker image in the tester logs

doc(tester): Link to the updated docker image for the testers

---

development-guide.md

Links https://fivetran.height.app/T-774825

Refactor(PartnerSdk): Proto Files Note On Release Version

---

README.md
doc-templates/destination-connector-templates/destination-overview-template.md
doc-templates/destination-connector-templates/destination-setup-guide-template.md
doc-templates/source-connector-templates/connector-overview-template.md
doc-templates/source-connector-templates/connector-setup-guide-template.md
doc-templates/style-guide/common-terms-glossary.md
doc-templates/style-guide/style-guide.md

Adds connector documentation templates, style guide and glossary as resources for Fivetran partners.

doc(SDK): Adding documentation resources for partners

---

README.md

for source and destination connectors

Correct template paths in README.md

---

README.md

Suggested text on the deploy process.
Close: https://fivetran.height.app/T-851331

doc(partner_sdk): add deploy expectations to the developer guide

---

development-guide.md
tools/connector-tester/README.md
tools/destination-tester/README.md

doc(Partner SDK): Add the documentation related to V2 proto changes

---

v2_examples/destination_sdk_v2.proto

feature(V2): V2 proto changes to support history mode

---

README.md

added Clickhouse as a reference open example

Update README.md - adding Clickhouse as an open example

---

development-guide.md
tools/destination-connector-tester/README.md

Closes https://fivetran.height.app/T-896299
Closes https://fivetran.height.app/T-896620

feature(partner_sdk): Update docs regarding alerts and history mode

---

examples/destination_connector/python/main.py
examples/source_connector/python/main.py

T-900063
> Source example
> Destination example

Fix import in python example

---

development-guide.md

Closes https://fivetran.height.app/T-901799

fix(development-guide): address the typo

---

development-guide.md

- Updated the destination connector docs to explaining  the `Capabilities` rpc call.
- Modified other statements for accuracy

docs: updated the destination connector docs

---

tools/source-connector-tester/README.md

Docs(Partner SDK): Fix broken link

---

examples/destination_connector/python/main.py

Link https://fivetran.height.app/T-900816
Adds batchHistory example for python destination.
Test:

Feature(PartnerSdk): Python Destination Batch History Example

---

README.md
doc-templates/destination-connector-templates/destination-overview-template.md
doc-templates/destination-connector-templates/destination-setup-guide-template.md
doc-templates/source-connector-templates/connector-overview-template.md
doc-templates/source-connector-templates/connector-setup-guide-template.md

Closes https://fivetran.height.app/T-930173

fix(docs): update readme and templates

---

development-guide.md

Closes T-932100
Added information on what is required from partners to help us build binary.

docs(Partner SDK): Provide instructions to partners for building binary

---

README.md

Closes https://fivetran.height.app/T-952333

feature(partner_sdk): Add Singlestore to publicly available list

---

development-guide.md

Change protobuf version in docs

feature(partner_sdk): Change protobuf version in docs

---

development-guide.md

Closes https://fivetran.height.app/T-889537
Improve docs around parquet file support

Docs(Partner SDK): Improve docs around parquet file support

---

development-guide.md
tools/destination-connector-tester/README.md
tools/source-connector-tester/README.md

Closes https://fivetran.atlassian.net/browse/RD-965340 https://fivetran.atlassian.net/browse/RD-965340
- Elaborate about checkpointing (Partners seem to not follow checkpointing best practices, for eg, this [instance](https://fivetran.slack.com/archives/C04NX344ZR9/p1748982329817649?thread_ts=1748615568.606669&cid=C04NX344ZR9))
- Mention clearly about ports when using tester (Partners were facing issues, for eg, this [instance](https://fivetran.slack.com/archives/C063CAUG9QW/p1749126563711399?thread_ts=1748367395.090869&cid=C063CAUG9QW)).

Docs(Partner SDK): Development guide improvements

---

development-guide/source-connector-development-guide.md

Links https://fivetran.atlassian.net/browse/RD-848365
Change:
Update doc for `selection_not_supported`.

feature(partner_sdk): Update doc for `selection_not_supported`

---

examples/source_connector/java/README.md
examples/source_connector/java/build.gradle

Link https://fivetran.atlassian.net/browse/RD-1023246

fix(partner_sdk): fix java source example

---

.gitignore
examples/source_connector/nodejs/README.md
examples/source_connector/nodejs/src/index.js

Link https://fivetran.atlassian.net/browse/RD-1023246
Testing

fix(partner_sdk): fix nodejs source example

---

how-to-handle-history-mode-batch-files.md

Closes https://fivetran.atlassian.net/browse/RD-928675
Add example for earliest start batch file for the history mode.

fix(partner-sdk): add example for earliest start batch file
